In [ ]:
import pandas as pd

# CARGA DE DATOS

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving a12completo.csv to a12completo.csv

In [ ]:
df = pd.read_csv("a12completo.csv", encoding="latin1",sep=";")

In [ ]:
df.head(20)

,id orig,anio,mes,dia,PROVINCIA,Rubro a12,facturacion,FECHA,operaciones,abrev_IATA,ISO3166_21,pobLACION_proy_2020,SUP km2,Facturacion_mill,REGION
0,1,2019,1,15,BUENOS AIRES,Anteojos,30878823,15/1/2019,8165,BA,NaN,17541141,307571,30.88,PAMPEANA
1,2,2019,1,4,BUENOS AIRES,Artículos de librería,4657723,4/1/2019,1096,BA,NaN,17541141,307571,4.66,PAMPEANA
2,3,2019,1,11,BUENOS AIRES,Balnearios,5839079,11/1/2019,1018,BA,NaN,17541141,307571,5.84,PAMPEANA
3,4,2019,1,15,BUENOS AIRES,Bicicletas,20645150,15/1/2019,1429,BA,NaN,17541141,307571,20.65,PAMPEANA
4,5,2019,1,19,BUENOS AIRES,Calzado y Marroquinería,229075801,19/1/2019,122273,BA,NaN,17541141,307571,229.08,PAMPEANA
5,6,2019,1,13,BUENOS AIRES,Colchones,53323671,13/1/2019,3441,BA,NaN,17541141,307571,53.32,PAMPEANA
6,7,2019,1,10,BUENOS AIRES,Electrodomésticos,439238382,10/1/2019,33880,BA,NaN,17541141,307571,439.24,PAMPEANA
7,8,2019,1,29,BUENOS AIRES,Indumentaria,1160938790,29/1/2019,573981,BA,NaN,17541141,307571,1160.94,NaN
8,9,2019,1,26,BUENOS AIRES,Instrumentos musicales,2273994,26/1/2019,256,BA,NaN,17541141,307571,2.27,NaN
9,10,2019,1,17,BUENOS AIRES,Juguetes y Juegos de mesa,68559650,17/1/2019,37150,BA,NaN,17541141,307571,68.56,NaN
10,11,2019,1,8,BUENOS AIRES,Libros,7189394,8/1/2019,2747,BA,NaN,17541141,307571,7.19,NaN
11,12,2019,1,13,BUENOS AIRES,Materiales para la construcción,374184123,13/1/2019,37390,BA,NaN,17541141,307571,374.18,NaN
12,13,2019,1,15,BUENOS AIRES,Motocicletas,927871,15/1/2019,51,BA,NaN,17541141,307571,0.93,PAMPEANA
13,14,2019,1,18,BUENOS AIRES,Motos y Bicicletas,150439725,18/1/2019,10834,BA,NaN,17541141,307571,150.44,PAMPEANA
14,15,2019,1,6,BUENOS AIRES,Muebles,159902472,6/1/2019,16236,BA,NaN,17541141,307571,159.90,PAMPEANA
15,16,2019,1,9,BUENOS AIRES,Sin clasificar,1262970,9/1/2019,115,BA,NaN,17541141,307571,1.26,PAMPEANA
16,17,2019,1,9,BUENOS AIRES,Teléfonos Celulares 4G,71962949,9/1/2019,7833,BA,NaN,17541141,307571,71.96,PAMPEANA
17,18,2019,1,3,BUENOS AIRES,Turismo,20546932,3/1/2019,1656,BA,NaN,17541141,307571,20.55,PAMPEANA
18,19,2019,1,17,CATAMARCA,Anteojos,492134,17/1/2019,121,CA,AR-K,415438,102602,0.49,NOA
19,20,2019,1,21,CATAMARCA,Artículos de librería,24048,21/1/2019,15,CA,AR-K,415438,102602,0.02,NOA

In [ ]:
df.tail(20)

,id orig,anio,mes,dia,PROVINCIA,Rubro a12,facturacion,FECHA,operaciones,abrev_IATA,ISO3166_21,pobLACION_proy_2020,SUP km2,Facturacion_mill,REGION
13543,13541,2021,4,18,TUCUMAN,Colchones,20422324,18/4/2021,730,TU,NaN,1694656,22524,20.42,NOA
13544,13542,2021,4,27,TUCUMAN,Computadoras. notebooks y tabletas,10960199,27/4/2021,379,TU,NaN,1694656,22524,10.96,NOA
13545,13543,2021,4,26,TUCUMAN,Electrodomésticos,225350982,26/4/2021,9325,TU,NaN,1694656,22524,225.35,NOA
13546,13544,2021,4,4,TUCUMAN,Equipamiento médico,797497,4/4/2021,5,TU,NaN,1694656,22524,0.80,NOA
13547,13545,2021,4,14,TUCUMAN,Indumentaria,364056785,14/4/2021,50625,TU,NaN,1694656,22524,364.06,NOA
13548,13546,2021,4,6,TUCUMAN,Instrumentos musicales,123065,6/4/2021,7,TU,NaN,1694656,22524,0.12,NOA
13549,13547,2021,4,27,TUCUMAN,Juguetes y Juegos de mesa,7079962,27/4/2021,1597,TU,NaN,1694656,22524,7.08,NOA
13550,13548,2021,4,5,TUCUMAN,Libros,2759563,5/4/2021,1103,TU,NaN,1694656,22524,2.76,NOA
13551,13549,2021,4,26,TUCUMAN,Máquinas y Herramientas,3845523,26/4/2021,188,TU,NaN,1694656,22524,3.85,NOA
13552,13550,2021,4,28,TUCUMAN,Materiales para la construcción,181229371,28/4/2021,6862,TU,NaN,1694656,22524,181.23,NOA
13553,13551,2021,4,12,TUCUMAN,Medicamentos,7538698,12/4/2021,1629,TU,NaN,1694656,22524,7.54,NOA
13554,13552,2021,4,21,TUCUMAN,Motocicletas,19840743,21/4/2021,454,TU,NaN,1694656,22524,19.84,NOA
13555,13553,2021,4,17,TUCUMAN,Muebles,61788817,17/4/2021,2593,TU,NaN,1694656,22524,61.79,NOA
13556,13554,2021,4,21,TUCUMAN,Neumáticos. accesorios y repuestos,34295660,21/4/2021,1149,TU,NaN,1694656,22524,34.30,NOA
13557,13555,2021,4,14,TUCUMAN,Perfumeria,4850232,14/4/2021,985,TU,NaN,1694656,22524,4.85,NOA
13558,13556,2021,4,29,TUCUMAN,Servicios de cuidado personal,306226,29/4/2021,27,TU,NaN,1694656,22524,0.31,NOA
13559,13557,2021,4,17,TUCUMAN,Servicios de preparacion para el deporte,754846,17/4/2021,34,TU,NaN,1694656,22524,0.75,NOA
13560,13558,2021,4,1,TUCUMAN,Servicios tecnicos de electronica y electrodom...,71050,1/4/2021,1,TU,NaN,1694656,22524,0.07,NOA
13561,13559,2021,4,16,TUCUMAN,Sin clasificar,14167573,16/4/2021,3067,TU,NaN,1694656,22524,14.17,NOA
13562,13560,2021,4,15,TUCUMAN,Turismo,276800,15/4/2021,42,TU,NaN,1694656,22524,0.28,NOA

In [ ]:
print("Número de filas y columnas:", df.shape)

Número de filas y columnas: (13563, 15)

In [ ]:
df.dtypes

id orig                  int64
anio                     int64
mes                      int64
  dia                    int64
PROVINCIA               object
Rubro a12               object
facturacion              int64
FECHA                   object
operaciones              int64
abrev_IATA              object
ISO3166_21              object
pobLACION_proy_2020      int64
SUP km2                  int64
Facturacion_mill       float64
REGION                  object
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13563 entries, 0 to 13562
Data columns (total 15 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id orig              13563 non-null  int64
 1   anio                 13563 non-null  int64
 2   mes                  13563 non-null  int64
 3     dia                13563 non-null  int64
 4   PROVINCIA            13563 non-null  object
 5   Rubro a12            13563 non-null  object
 6   facturacion          13563 non-null  int64
 7   FECHA                13563 non-null  object
 8   operaciones          13563 non-null  int64
 9   abrev_IATA           13563 non-null  object
 10  ISO3166_21           5718 non-null   object
 11  pobLACION_proy_2020  13563 non-null  int64
 12  SUP km2              13563 non-null  int64
 13  Facturacion_mill     13563 non-null  float64
 14  REGION               13549 non-null  object
dtypes: float64(1), int64(8), object(6)
memory usage: 1.6+ MB

In [ ]:
df.describe()

,id orig,anio,mes,dia,facturacion,operaciones,pobLACION_proy_2020,SUP km2,Facturacion_mill
count,13563.000000,13563.000000,13563.000000,13563.000000,1.356300e+04,1.356300e+04,1.356300e+04,13563.000000,13563.000000
mean,6779.018727,2019.815306,6.090835,15.455873,8.572919e+07,1.013330e+04,2.043393e+06,125056.440832,85.729172
std,3915.413020,0.715366,3.572104,8.597920,4.405659e+08,6.033551e+04,3.615487e+06,75035.133853,440.565874
min,1.000000,2019.000000,1.000000,1.000000,1.000000e+00,1.000000e+00,1.734320e+05,203.000000,0.000000
25%,3388.500000,2019.000000,3.000000,8.000000,8.031550e+05,8.950000e+01,6.051930e+05,78781.000000,0.800000
50%,6779.000000,2020.000000,6.000000,15.000000,4.681694e+06,5.360000e+02,9.783130e+05,102602.000000,4.680000
75%,10169.500000,2020.000000,9.000000,23.000000,2.879241e+07,3.057500e+03,1.694656e+06,165321.000000,28.795000
max,13560.000000,2021.000000,12.000000,31.000000,1.069319e+10,2.193473e+06,1.754114e+07,307571.000000,10693.190000

# 2 INSPECCION DE COLUMNAS

In [ ]:
df.columns

Index(['id orig', 'anio', 'mes', '  dia', 'PROVINCIA', 'Rubro a12',
       'facturacion', 'FECHA', 'operaciones', 'abrev_IATA', 'ISO3166_21',
       'pobLACION_proy_2020', 'SUP km2', 'Facturacion_mill   ', 'REGION'],
      dtype='object')

In [ ]:
for col in df.columns:
    print(f"Columna: {col},    Tipo de dato: {df[col].dtype}")

Columna: id orig,    Tipo de dato: int64
Columna: anio,    Tipo de dato: int64
Columna: mes,    Tipo de dato: int64
Columna:   dia,    Tipo de dato: int64
Columna: PROVINCIA,    Tipo de dato: object
Columna: Rubro a12,    Tipo de dato: object
Columna: facturacion,    Tipo de dato: int64
Columna: FECHA,    Tipo de dato: object
Columna: operaciones,    Tipo de dato: int64
Columna: abrev_IATA,    Tipo de dato: object
Columna: ISO3166_21,    Tipo de dato: object
Columna: pobLACION_proy_2020,    Tipo de dato: int64
Columna: SUP km2,    Tipo de dato: int64
Columna: Facturacion_mill   ,    Tipo de dato: float64
Columna: REGION,    Tipo de dato: object

In [ ]:
import re

In [ ]:
df2 = df.copy()
df2.columns = df.columns.str.replace(' ', '_')

# MODIFICACION DE COLUMNAS

In [ ]:
df2.head()

,id_orig,anio,mes,__dia,PROVINCIA,Rubro_a12,facturacion,FECHA,operaciones,abrev_IATA,ISO3166_21,pobLACION_proy_2020,SUP_km2,Facturacion_mill___,REGION
0,1,2019,1,15,BUENOS AIRES,Anteojos,30878823,15/1/2019,8165,BA,NaN,17541141,307571,30.88,PAMPEANA
1,2,2019,1,4,BUENOS AIRES,Artículos de librería,4657723,4/1/2019,1096,BA,NaN,17541141,307571,4.66,PAMPEANA
2,3,2019,1,11,BUENOS AIRES,Balnearios,5839079,11/1/2019,1018,BA,NaN,17541141,307571,5.84,PAMPEANA
3,4,2019,1,15,BUENOS AIRES,Bicicletas,20645150,15/1/2019,1429,BA,NaN,17541141,307571,20.65,PAMPEANA
4,5,2019,1,19,BUENOS AIRES,Calzado y Marroquinería,229075801,19/1/2019,122273,BA,NaN,17541141,307571,229.08,PAMPEANA

In [ ]:
df2.columns

Index(['id_orig', 'anio', 'mes', '__dia', 'PROVINCIA', 'Rubro_a12',
       'facturacion', 'FECHA', 'operaciones', 'abrev_IATA', 'ISO3166_21',
       'pobLACION_proy_2020', 'SUP_km2', 'Facturacion_mill___', 'REGION'],
      dtype='object')

In [ ]:

# ELIMINANDO ESPACIOS EN BLANCO

df.columns = df.columns.str.strip()


df.columns = [re.sub(r'\s+', '_', col) for col in df.columns]

df.head()

,id_orig,anio,mes,dia,PROVINCIA,Rubro_a12,facturacion,FECHA,operaciones,abrev_IATA,ISO3166_21,pobLACION_proy_2020,SUP_km2,Facturacion_mill,REGION
0,1,2019,1,15,BUENOS AIRES,Anteojos,30878823,15/1/2019,8165,BA,NaN,17541141,307571,30.88,PAMPEANA
1,2,2019,1,4,BUENOS AIRES,Artículos de librería,4657723,4/1/2019,1096,BA,NaN,17541141,307571,4.66,PAMPEANA
2,3,2019,1,11,BUENOS AIRES,Balnearios,5839079,11/1/2019,1018,BA,NaN,17541141,307571,5.84,PAMPEANA
3,4,2019,1,15,BUENOS AIRES,Bicicletas,20645150,15/1/2019,1429,BA,NaN,17541141,307571,20.65,PAMPEANA
4,5,2019,1,19,BUENOS AIRES,Calzado y Marroquinería,229075801,19/1/2019,122273,BA,NaN,17541141,307571,229.08,PAMPEANA

In [ ]:
df.columns

Index(['id_orig', 'anio', 'mes', 'dia', 'PROVINCIA', 'Rubro_a12',
       'facturacion', 'FECHA', 'operaciones', 'abrev_IATA', 'ISO3166_21',
       'pobLACION_proy_2020', 'SUP_km2', 'Facturacion_mill', 'REGION'],
      dtype='object')

In [ ]:
# AHORA LOS PÀSO A MINUSCULA
df.columns = df.columns.str.lower()
df.head()

,id_orig,anio,mes,dia,provincia,rubro_a12,facturacion,fecha,operaciones,abrev_iata,iso3166_21,poblacion_proy_2020,sup_km2,facturacion_mill,region
0,1,2019,1,15,BUENOS AIRES,Anteojos,30878823,15/1/2019,8165,BA,NaN,17541141,307571,30.88,PAMPEANA
1,2,2019,1,4,BUENOS AIRES,Artículos de librería,4657723,4/1/2019,1096,BA,NaN,17541141,307571,4.66,PAMPEANA
2,3,2019,1,11,BUENOS AIRES,Balnearios,5839079,11/1/2019,1018,BA,NaN,17541141,307571,5.84,PAMPEANA
3,4,2019,1,15,BUENOS AIRES,Bicicletas,20645150,15/1/2019,1429,BA,NaN,17541141,307571,20.65,PAMPEANA
4,5,2019,1,19,BUENOS AIRES,Calzado y Marroquinería,229075801,19/1/2019,122273,BA,NaN,17541141,307571,229.08,PAMPEANA

In [ ]:
df.columns

Index(['id_orig', 'anio', 'mes', 'dia', 'provincia', 'rubro_a12',
       'facturacion', 'fecha', 'operaciones', 'abrev_iata', 'iso3166_21',
       'poblacion_proy_2020', 'sup_km2', 'facturacion_mill', 'region'],
      dtype='object')

lAS VARIABLES EN EL CONTEXTO AHORA 12 SIGNIFICAN

# 3 ANALISIS

In [ ]:
#DETECTAR VALOSRES NULOS

df.isnull().sum()

id_orig                   0
anio                      0
mes                       0
dia                       0
provincia                 0
rubro_a12                 0
facturacion               0
fecha                     0
operaciones               0
abrev_iata                0
iso3166_21             7845
poblacion_proy_2020       0
sup_km2                   0
facturacion_mill          0
region                   14
dtype: int64

In [ ]:
#AHORA EN PORCENTAJES
datanull = df.isnull().sum()
data_porcentaje = (datanull / len(df)) * 100
print("Porcentaje de datos faltantes por columna:\n", data_porcentaje)

Porcentaje de datos faltantes por columna:
 id_orig                 0.000000
anio                    0.000000
mes                     0.000000
dia                     0.000000
provincia               0.000000
rubro_a12               0.000000
facturacion             0.000000
fecha                   0.000000
operaciones             0.000000
abrev_iata              0.000000
iso3166_21             57.841186
poblacion_proy_2020     0.000000
sup_km2                 0.000000
facturacion_mill        0.000000
region                  0.103222
dtype: float64

In [ ]:
umbral = 0.30
dflimpio = df.dropna(thresh=int((1-umbral)*df.shape[0]), axis=1)
dflimpio.head()

,id_orig,anio,mes,dia,provincia,rubro_a12,facturacion,fecha,operaciones,abrev_iata,poblacion_proy_2020,sup_km2,facturacion_mill,region
0,1,2019,1,15,BUENOS AIRES,Anteojos,30878823,15/1/2019,8165,BA,17541141,307571,30.88,PAMPEANA
1,2,2019,1,4,BUENOS AIRES,Artículos de librería,4657723,4/1/2019,1096,BA,17541141,307571,4.66,PAMPEANA
2,3,2019,1,11,BUENOS AIRES,Balnearios,5839079,11/1/2019,1018,BA,17541141,307571,5.84,PAMPEANA
3,4,2019,1,15,BUENOS AIRES,Bicicletas,20645150,15/1/2019,1429,BA,17541141,307571,20.65,PAMPEANA
4,5,2019,1,19,BUENOS AIRES,Calzado y Marroquinería,229075801,19/1/2019,122273,BA,17541141,307571,229.08,PAMPEANA

In [ ]:
dflimpio.columns

Index(['id_orig', 'anio', 'mes', 'dia', 'provincia', 'rubro_a12',
       'facturacion', 'fecha', 'operaciones', 'abrev_iata',
       'poblacion_proy_2020', 'sup_km2', 'facturacion_mill', 'region'],
      dtype='object')

Eliminaria la columna ISO3166_21 debido a que supera el umbral de datos faltantes preestablecido en 0.3

In [ ]:
#CAMBIO EL TIPO DE DATO DE FACTURACION
df['facturacion'] = df['facturacion'].astype(float)
df.dtypes

id_orig                  int64
anio                     int64
mes                      int64
dia                      int64
provincia               object
rubro_a12               object
facturacion            float64
fecha                   object
operaciones              int64
abrev_iata              object
iso3166_21              object
poblacion_proy_2020      int64
sup_km2                  int64
facturacion_mill       float64
region                  object
dtype: object

In [ ]:
df["facturacion_promedio_por_operacion"] = df['facturacion']/df["operaciones"]
df.head()

,id_orig,anio,mes,dia,provincia,rubro_a12,facturacion,fecha,operaciones,abrev_iata,iso3166_21,poblacion_proy_2020,sup_km2,facturacion_mill,region,facturacion_promedio_por_operacion
0,1,2019,1,15,BUENOS AIRES,Anteojos,30878823.0,15/1/2019,8165,BA,NaN,17541141,307571,30.88,PAMPEANA,3781.852174
1,2,2019,1,4,BUENOS AIRES,Artículos de librería,4657723.0,4/1/2019,1096,BA,NaN,17541141,307571,4.66,PAMPEANA,4249.747263
2,3,2019,1,11,BUENOS AIRES,Balnearios,5839079.0,11/1/2019,1018,BA,NaN,17541141,307571,5.84,PAMPEANA,5735.833988
3,4,2019,1,15,BUENOS AIRES,Bicicletas,20645150.0,15/1/2019,1429,BA,NaN,17541141,307571,20.65,PAMPEANA,14447.270819
4,5,2019,1,19,BUENOS AIRES,Calzado y Marroquinería,229075801.0,19/1/2019,122273,BA,NaN,17541141,307571,229.08,PAMPEANA,1873.478209

In [ ]:
df["densidad_poblacional"] = df['poblacion_proy_2020']/df['sup_km2']
df.head()

,id_orig,anio,mes,dia,provincia,rubro_a12,facturacion,fecha,operaciones,abrev_iata,iso3166_21,poblacion_proy_2020,sup_km2,facturacion_mill,region,facturacion_promedio_por_operacion,densidad_poblaciona,densidad_poblacional
0,1,2019,1,15,BUENOS AIRES,Anteojos,30878823.0,15/1/2019,8165,BA,NaN,17541141,307571,30.88,PAMPEANA,3781.852174,57.031193,57.031193
1,2,2019,1,4,BUENOS AIRES,Artículos de librería,4657723.0,4/1/2019,1096,BA,NaN,17541141,307571,4.66,PAMPEANA,4249.747263,57.031193,57.031193
2,3,2019,1,11,BUENOS AIRES,Balnearios,5839079.0,11/1/2019,1018,BA,NaN,17541141,307571,5.84,PAMPEANA,5735.833988,57.031193,57.031193
3,4,2019,1,15,BUENOS AIRES,Bicicletas,20645150.0,15/1/2019,1429,BA,NaN,17541141,307571,20.65,PAMPEANA,14447.270819,57.031193,57.031193
4,5,2019,1,19,BUENOS AIRES,Calzado y Marroquinería,229075801.0,19/1/2019,122273,BA,NaN,17541141,307571,229.08,PAMPEANA,1873.478209,57.031193,57.031193

# ANALISIS EXPLORATORIO SENCILLO

In [ ]:
facturacion_promedio_total = df['facturacion'].mean()
print("Facturación promedio total: ", facturacion_promedio_total)

Facturación promedio total:  85729189.65133083

In [ ]:
facturacion_promedio_por_provincia = df.groupby('provincia')['facturacion'].mean()

facturacion_promedio_por_provincia

provincia
BUENOS AIRES                       5.501462e+08
CATAMARCA                          4.103871e+06
CHACO                              2.330938e+07
CHUBUT                             2.177491e+07
CIUDAD AUTONOMA DE BUENOS AIRES    6.231801e+08
CORDOBA                            1.378488e+08
CORRIENTES                         1.406237e+07
ENTRE RIOS                         3.469115e+07
FORMOSA                            5.895963e+06
JUJUY                              1.058692e+07
LA PAMPA                           1.197893e+07
LA RIOJA                           3.519621e+06
MENDOZA                            5.624389e+07
MISIONES                           1.352762e+07
NEUQUEN                            2.887669e+07
RIO NEGRO                          2.315405e+07
SALTA                              2.770387e+07
SAN JUAN                           1.485363e+07
SAN LUIS                           1.173892e+07
SANTA CRUZ                         1.013711e+07
SANTA FE                           1.719820e+08
SANTIAGO DEL ESTERO                1.117226e+07
TIERRA DEL FUEGO                   1.337770e+07
TUCUMAN                            4.061814e+07
Name: facturacion, dtype: float64

In [ ]:

min_facturacion = df['facturacion'].min()
max_facturacion = df['facturacion'].max()
rango = max_facturacion - min_facturacion
print("Rango de facturación: ", rango)

Rango de facturación:  10693186276.0

In [ ]:
dflimpio = df.copy()
dflimpio.head()

,id_orig,anio,mes,dia,provincia,rubro_a12,facturacion,fecha,operaciones,abrev_iata,iso3166_21,poblacion_proy_2020,sup_km2,facturacion_mill,region,facturacion_promedio_por_operacion,densidad_poblaciona,densidad_poblacional
0,1,2019,1,15,BUENOS AIRES,Anteojos,30878823.0,15/1/2019,8165,BA,NaN,17541141,307571,30.88,PAMPEANA,3781.852174,57.031193,57.031193
1,2,2019,1,4,BUENOS AIRES,Artículos de librería,4657723.0,4/1/2019,1096,BA,NaN,17541141,307571,4.66,PAMPEANA,4249.747263,57.031193,57.031193
2,3,2019,1,11,BUENOS AIRES,Balnearios,5839079.0,11/1/2019,1018,BA,NaN,17541141,307571,5.84,PAMPEANA,5735.833988,57.031193,57.031193
3,4,2019,1,15,BUENOS AIRES,Bicicletas,20645150.0,15/1/2019,1429,BA,NaN,17541141,307571,20.65,PAMPEANA,14447.270819,57.031193,57.031193
4,5,2019,1,19,BUENOS AIRES,Calzado y Marroquinería,229075801.0,19/1/2019,122273,BA,NaN,17541141,307571,229.08,PAMPEANA,1873.478209,57.031193,57.031193

In [ ]:


# Guardar el DataFrame resultante en un nuevo archivo llamado datos_limpios.csv
dflimpio.to_csv('datos_limpios.csv', index=False)

# Descargar el archivo
files.download('datos_limpios.csv')